### ISSUE TITLE
做了个这个。帮忙处理一下

### ISSUE THREAD

**Issue by cgoxopx** [Erblocker/Pandora-magicbox#2]
https://github.com/cgoxopx/Pandora-magicbox  
项目太大，没法clone，于是就直接fork，然后再清空我那边分支。    
结果发现就没法合并了。

**Comment by cgoxopx** [comment]
可以直接用它覆盖掉平板上的find之类的东西，实现开机启动。

**Comment by chainsx** [comment]
你知道安卓无root设备怎么添加resolv.conf来实现dns解析吗？
尤其是运行某些已编译二进制可执行文件时，例如busybox的nslookup

**Comment by cgoxopx** [comment]
没root的话，不清楚
