### ISSUE TITLE
关于xxx.lexuewang.cn:8002的问题

### ISSUE THREAD

**Issue by chainsx** [Erblocker/Pandora-magicbox#6]
现在据我的了解，这应该是更改密码以及附带其他内容的用途
如下
http://ruiyi.lexuewang.cn:8002/static/UI_win7/js/login.js
分析源码时的推测，
但始终没能登陆上去

**Comment by cgoxopx** [comment]
我感觉跟睿易云拍有关。

**Comment by chainsx** [comment]
没有吧！
你看那个js脚本

**Comment by chainsx** [comment]
不可能与云拍相关

**Comment by chainsx** [comment]
根据抓包时的推测

**Comment by chainsx** [comment]
根据抓包时的推测
但是[这是](https://github.com/chainsx/chainsx-DD/raw/master/test/mitmproxy.jpg)登录不上的原因
